@baseUrl = http://localhost:5000
###
GET {{baseUrl}}/contexts

###
GET {{baseUrl}}/contexts/1

###
POST {{baseUrl}}/contexts
Content-Type: application/json

{
    "name": "Test Context 1",
    "icon_id": 1
}

###
PUT {{baseUrl}}/contexts/1
Content-Type: application/json

{
    "id": 1,
    "name": "Context 1",
    "icon_id": 1,
    "deleted": false    
}

###
DELETE {{baseUrl}}/contexts/1

